### ISSUE TITLE
pip install -r .\requirements.txt not longer working

### ISSUE THREAD

**Issue by XaRz** [ghostcodekc/tamriel-trade-bot#9]
Hello, 

I'm wondering If we could make it work now with python 3.12

I' receiving this with the pip install -r requeriments.txt:

```PS C:\Users\perec\Downloads\tamriel-trade-bot-master\tamriel-trade-bot-master> pip install -r .\requirements.txt
Collecting astroid==2.4.2 (from -r .\requirements.txt (line 1))
  Using cached astroid-2.4.2-py3-none-any.whl.metadata (3.9 kB)
Collecting autopep8==1.5.3 (from -r .\requirements.txt (line 2))
  Using cached autopep8-1.5.3.tar.gz (116 kB)
  Preparing metadata (setup.py) ... done
Collecting backcall==0.2.0 (from -r .\requirements.txt (line 3))
  Using cached backcall-0.2.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting beautifulsoup4==4.9.1 (from -r .\requirements.txt (line 4))
  Using cached beautifulsoup4-4.9.1-py3-none-any.whl.metadata (4.1 kB)
Collecting boto3==1.13.16 (from -r .\requirements.txt (line 5))
  Using cached boto3-1.13.16-py2.py3-none-any.whl.metadata (4.7 kB)
Collecting botocore==1.16.16 (from -r .\requirements.txt (line 6))
  Using cached botocore-1.16.16-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting certifi==2020.6.20 (from -r .\requirements.txt (line 7))
  Using cached certifi-2020.6.20-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting chardet==3.0.4 (from -r .\requirements.txt (line 8))
  Using cached chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting colorama==0.4.3 (from -r .\requirements.txt (line 9))
  Using cached colorama-0.4.3-py2.py3-none-any.whl.metadata (14 kB)
Collecting decorator==4.4.2 (from -r .\requirements.txt (line 10))
  Using cached decorator-4.4.2-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting docutils==0.15.2 (from -r .\requirements.txt (line 11))
  Using cached docutils-0.15.2-py3-none-any.whl.metadata (2.6 kB)
Collecting idna==2.10 (from -r .\requirements.txt (line 12))
  Using cached idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting ipykernel==5.3.4 (from -r .\requirements.txt (line 13))
  Using cached ipykernel-5.3.4-py3-none-any.whl.metadata (1.0 kB)
Collecting ipython==7.16.1 (from -r .\requirements.txt (line 14))
  Using cached ipython-7.16.1-py3-none-any.whl.metadata (4.4 kB)
Collecting ipython-genutils==0.2.0 (from -r .\requirements.txt (line 15))
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Collecting isort==4.3.21 (from -r .\requirements.txt (line 16))
  Using cached isort-4.3.21-py2.py3-none-any.whl.metadata (19 kB)
Collecting jedi==0.17.2 (from -r .\requirements.txt (line 17))
  Using cached jedi-0.17.2-py2.py3-none-any.whl.metadata (19 kB)
Collecting jmespath==0.10.0 (from -r .\requirements.txt (line 18))
  Using cached jmespath-0.10.0-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting jupyter-client==6.1.6 (from -r .\requirements.txt (line 19))
  Using cached jupyter_client-6.1.6-py3-none-any.whl.metadata (3.9 kB)
Collecting jupyter-core==4.6.3 (from -r .\requirements.txt (line 20))
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl.metadata (850 bytes)
Collecting lazy-object-proxy==1.4.3 (from -r .\requirements.txt (line 21))
  Using cached lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml>=4.6.3 (from -r .\requirements.txt (line 22))
  Using cached lxml-5.2.1-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting mccabe==0.6.1 (from -r .\requirements.txt (line 23))
  Using cached mccabe-0.6.1-py2.py3-none-any.whl.metadata (4.3 kB)
Collecting numpy==1.19.1 (from -r .\requirements.txt (line 24))
  Using cached numpy-1.19.1.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      Running from numpy source directory.
      <string>:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py:73: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.21')
      C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      performance hint: _common.pyx:275:19: Exception check after calling 'random_func' will always require the GIL to be acquired. Declare 'random_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:299:19: Exception check after calling 'random_func' will always require the GIL to be acquired. Declare 'random_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:322:50: Exception check after calling 'random_func' will always require the GIL to be acquired. Declare 'random_func' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:426:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:465:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:509:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:592:36: Exception check after calling 'f0' will always require the GIL to be acquired. Declare 'f0' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:596:36: Exception check after calling 'f1' will always require the GIL to be acquired. Declare 'f1' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:600:36: Exception check after calling 'f2' will always require the GIL to be acquired. Declare 'f2' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:604:36: Exception check after calling 'f3' will always require the GIL to be acquired. Declare 'f3' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:638:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:675:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:712:63: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:754:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:785:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:903:40: Exception check after calling 'f0' will always require the GIL to be acquired. Declare 'f0' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:907:40: Exception check after calling 'fd' will always require the GIL to be acquired. Declare 'fd' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:911:41: Exception check after calling 'fdd' will always require the GIL to be acquired. Declare 'fdd' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:916:40: Exception check after calling 'fi' will always require the GIL to be acquired. Declare 'fi' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:920:41: Exception check after calling 'fdi' will always require the GIL to be acquired. Declare 'fdi' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:924:38: Exception check after calling 'fiii' will always require the GIL to be acquired. Declare 'fiii' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:960:31: Exception check after calling 'f' will always require the GIL to be acquired. Declare 'f' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _common.pyx:1002:32: Exception check after calling 'f1' will always require the GIL to be acquired. Declare 'f1' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
      performance hint: _generator.pyx:707:41: Exception check after calling '_shuffle_int' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_shuffle_int' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_shuffle_int' to allow an error code to be returned.
      performance hint: _generator.pyx:736:45: Exception check after calling '_shuffle_int' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare '_shuffle_int' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on '_shuffle_int' to allow an error code to be returned.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i

              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------

      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Traceback (most recent call last):
        File "C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py", line 235, in <module>
          main()
        File "C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "C:\Users\perec\AppData\Local\Temp\pip-install-w91oeal3\numpy_1d4337a5dd5a424eb0a66f6cdea84be0\tools\cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "C:\Users\perec\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\perec\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "C:\Users\perec\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\perec\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\perec\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\perec\AppData\Local\Temp\pip-build-env-7w_r_8xo\overlay\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\perec\AppData\Local\Temp\pip-build-env-7w_r_8xo\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\perec\AppData\Local\Temp\pip-build-env-7w_r_8xo\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 499, in <module>
        File "<string>", line 479, in setup_package
        File "<string>", line 274, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]```

      
Can you help me?

**Comment by ghostcodekc** [comment]
I'd suggest using Python 3.8.5. I don't have any plans to update this. You can fork it or open a PR when you get it working and I'll merge it in.
